import os
API_ID = os.environ.get("API_ID", None) 
API_HASH = os.environ.get("API_HASH", None) 
BOT_TOKEN = os.environ.get("BOT_TOKEN", None) 
OPENAI_KEY = os.environ.get("OPENAI_KEY",None)
BOT_USERNAME = os.environ.get("BOT_USERNAME" ,"Sexyaadityabot") 
SUDO=os.environ.get("SUDO","5307865914")
BOT_NAME = os.environ.get("BOT_NAME","AADITYA PVT CHATGPT")
START_IMG = os.environ.get("START_IMG","https://graph.org/file/c66656541bb0d93679a91.jpg")
STKR = os.environ.get("STKR","CAACAgUAAx0Cbc0hiAACCCdkGV8SLh6npK6iqSIjFAAB-YeJG-gAAlcIAAIHn-FU-nC7zlMxNzQvBA")
BANNED_USERS=os.environ.get("BANNED_USERS",None)
UPDATE_CHNL = os.environ.get("UPDATE_CHNL","TH3ONLYCHANNEL")
# OWNER_USERNAME = os.environ.get("OWNER_USERNAME","SexyAaditya")
SUDO=os.environ.get("SUDO","5307865914")
SUPPORT_GRP = os.environ.get("SUPPORT_GRP","TH3ONLYCHANNEL")
